---
- name: Wait for domain {{ rhde_builder_vm_name }} IP address
  become: true
  shell: >-
    virsh domifaddr {{ rhde_builder_vm_name }} --source arp |
      awk '/ipv4/ { gsub("/.*", "", $4); print $4 }'
  register: rhde_builder_ip_address
  until: "rhde_builder_ip_address.stdout_lines"
  retries: 60
  delay: 1

- name: Register the {{ rhde_builder_vm_name }} as a new ansible host
  add_host:
    name: "{{ rhde_builder_vm_name }}"
    ansible_host: "{{ rhde_builder_ip_address.stdout }}"
    ansible_user: root
    ansible_ssh_private_key_file: "{{ rhde_builder_ssh_privkey }}"
    ansible_ssh_command_args: "-o StrictHostKeyChecking=no"
    groups: rhde_builder

- name: Get {{ rhde_builder_vm_name }} facts etc.
  setup:
  delegate_to: "{{ rhde_builder_vm_name }}"
  delegate_facts: true
...
