---
- name: Check if the domain {{ rhde_builder_vm_name }} exists
  become: true
  community.libvirt.virt:
    command: info
  register: rhde_builder_vms_list

- name: Remove the {{ rhde_builder_vm_name }} domain completely
  when: "rhde_builder_vm_name in rhde_builder_vms_list.keys()"
  block:
  - name: Add {{ rhde_builder_vm_name }} to the inventory (if running)
    include_tasks: add_rhde_builder_vm_to_inventory.yml
    when: "rhde_builder_vms_list[rhde_builder_vm_name]['state'] == 'running'"

  - name: Unregister from RHSM
    delegate_to: "{{ rhde_builder_vm_name }}"
    community.general.redhat_subscription:
      state: absent
    when: "rhde_builder_vm_name in lookup('ansible.builtin.inventory_hostnames', rhde_builder_vm_name)"

  - name: Destroy the domain
    become: true
    community.libvirt.virt:
      name: "{{ rhde_builder_vm_name }}"
      command: destroy
    when: "rhde_builder_vms_list[rhde_builder_vm_name]['state'] == 'running'"

  - name: Undefine the domain
    become: true
    community.libvirt.virt:
      name: "{{ rhde_builder_vm_name }}"
      command: undefine

- name: Remove the base RHEL image
  become: true
  file:
    path: "{{ rhde_builder_base_image_file }}"
    state: absent
  when: rhde_builder_cleanup_remove_base_rhel_image
...
