---
- name: Setup Repositories
  community.general.rhsm_repository:
    state: enabled
    purge: true
    name:
      - rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
      - rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms
  become: true

- name: Install Packages needed by the composer-cli
  ansible.builtin.package:
    state: latest
    name:
      - osbuild-composer
      - composer-cli
      - cockpit-composer
      - bash-completion
      - firewalld
      - podman
      - lorax
      - rsync
  become: true

- name: Enable Cockpit/Composer/Firewalld
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  loop:
    - osbuild-composer.socket
    - cockpit.socket
  become: true
...
